// import 'dart:convert';

// import 'package:flutter_application_3/api/api_const.dart';
// import 'package:flutter_application_3/api/sources_model.dart';
// import 'package:http/http.dart' as http;
// class ApiServices {
//   static Future<Autogenerated> getSources(String categoryId) async{
//     var url = Uri.https(ApiConsts.baseUrl,ApiConsts.sourcesEndpoint,
//     {'apiKey': ApiConsts.apiKey, 'category': categoryId}
//     );
//    var responce = await  http.get(url);
//   String body=  responce.body;
//   var json= jsonDecode(body);
//   return Autogenerated.fromJson(json);
//   }
// }
import 'dart:convert';

import 'package:flutter_application_3/datamodel/News_responce/NewsResponse.dart';
import 'package:flutter_application_3/datamodel/source_responce/SourceResponse.dart';
import 'package:http/http.dart' as http;


class ApiManger {
  static const String baseUrl = 'newsapi.org';

  static const String apiKey = 'b79ddb3a3eac45b6a3c9271f0c943471';

  static Future<SourceResponse> getSources(String categoryId) async {
    var uri = Uri.https(baseUrl, '/v2/top-headlines/sources', {
      'apiKey': apiKey,
      'category': categoryId,
    });
    var response = await http.get(uri);
    var json = jsonDecode(response.body);
    SourceResponse sourceResponse = SourceResponse.fromJson(json);
    return sourceResponse;
  }

  static Future<NewsResponse> getNews(String sourceId) async {
    var uri = Uri.https(baseUrl, '/v2/everything', {
      'apiKey': apiKey,
      'sources': sourceId,
    });
    var response = await http.get(uri);
    var json = jsonDecode(response.body);
    NewsResponse newsResponse = NewsResponse.fromJson(json);
    return newsResponse;
  }
}